server:
  port: 3344
spring:
  application:
    name: config-server

  cloud:
    config:
      label: main  #读取的分支
      server:
        git:
          uri: https://github.com/xiaoyull/springcloudConfig.git #通过秘钥然后得到的地址
          search-paths:
            - springcloudConfig #那个级别的目录

  rabbitmq: #配置rabbitmq，用于消息总线服务
    host: localhost
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    fetchRegistry: true #是否从Eureka注册中心抓取已有的服务，默认是true，
    #但是集群必须是true才可以配合ribbon做负载均衡
    register-with-eureka: true #向eureka注册中心注册自己
    service-url: #eureka注册中心地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群配置，往多个注册中心都注册
  instance:
    instance-id: configserver #设置Eureka注册中心web页面中Status中名称
    prefer-ip-address: true # 是否显示ip地址
    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
# rabbitmq相关配置，暴露bus服务端总线刷新配置的端点
#修改后的配置:
##rabbitmq相关配置 ,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
  endpoint:
    bus-env:
      enabled: true
      bus-refresh:
        enabled: true
