server:
  port: 83
spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址，将服务注册到nacos中
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
service-url:
  nacos-user-service: http://nacos-provider-payment #生产者服务名，用于远程调用
