server:
  port: 9002
spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #告诉微服务，nacos的访问地址
        server-addr: http://192.168.0.105:8080/ #告诉微服务，nacos的集群地址

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露端点

