server:
  port: 9002
spring:
  application:
    name: nacos-provider-payment
  datasource:
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: woyu1996
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露端点
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yu.springcloud.entities
